<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.itzimo.project.initializer</groupId>
    <artifactId>project-initializer-common-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.0.2</spring-boot.version>
        <fastjson2.version>2.0.53</fastjson2.version>
        <mybatis-plus.version>3.5.14</mybatis-plus.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <!--模块版本管理-->
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-common-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-repository-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-repository</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-manager-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-manager</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-service-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-service</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.itzimo.project.initializer</groupId>
                <artifactId>project-initializer-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <!--springboot版本-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2-extension-spring6</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>